 setDemo.citySet();
 setDemo.randomIntegrSet();


 List<integer> listInteger = new list<integer>();
 
        listInteger.add(10);
        listInteger.add(15);
        listInteger.add(21);
        listInteger.add(15);
        listInteger.add(15);
 
 set<integer> setInteger = setDemo.setFromList(listInteger);
 system.debug('set --->'+ setinteger);

   
        //returnSet is parametr inside caseSet

 setDemo.caseSet();
 
        







